stages:
  - merge
merge:
  stage: merge
  tags:
    - pan
  timeout: 2 hours 0 minutes
  before_script:
    - test -f Miniconda3-latest-Linux-x86_64.sh || wget -nv http://anaconda.rdhpcs.noaa.gov/miniconda/Miniconda3-latest-Linux-x86_64.sh
    - bash Miniconda3-latest-Linux-x86_64.sh -b -p `pwd`/local_env
    - export PATH=`pwd`/local_env/bin:$PATH
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
    - conda env create --file repro-pan.yml
    - . activate repro
    - conda list -e
    - cp /archive/gold/datasets/topography/GEBCO_2020/GEBCO_2020.nc4 ./GEBCO_2020.nc
    #- curl -o gebco_2020_netcdf.zip https://www.bodc.ac.uk/data/open_download/gebco/gebco_2020/zip/
    #- unzip gebco_2020_netcdf.zip
  script:
    - export PATH=`pwd`/local_env/bin:$PATH
    - export PATH=`pwd`/local_env/envs/repro/bin:$PATH
    - . activate repro
    - python -m ipykernel install --user --name repro --display-name "Py3-repro"
    - conda info -e
    - papermill Merge_Bedmachine+Gebco2.ipynb
    - md5sum -c checksums.txt
